AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A device model service for CRUD operations on IOT device model metadata
Globals:
  Function:
    Timeout: 5
Resources:
  DeviceModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://device-model-lambda/346e00e6f7e9f9b1f53cb14517f2d116
      Handler: devicemodel
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /devicemodels
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
Outputs:
  DeviceModelAPI:
    Description: API Gateway endpoint URL for Dev environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/devicemodels/
  DeviceModelFunction:
    Description: Device Model Dev Service which will function as a device model metadata
      service e.g. Trio 8300 etc
    Value:
      Fn:::GetAtt:
      - DeviceModelFunction.Arn
      - Arn
  DeviceModelFunctionIamRole:
    Description: Implicit IAM Role created for Device Model function
    Value:
      Fn:::GetAtt:
      - DeviceModelFunction.Arn
      - Arn
